import type { Country, CountryKnowledgeEntry } from '../../core/data/country.types';

export const FIXTURE_COUNTRIES: Country[] = [
  {
    id: 'es',
    iso2: 'ES',
    names: { en: 'Spain', ru: 'Spain' },
    capitals: { en: 'Madrid', ru: 'Madrid' },
    continent: 'europe',
    lat: 40,
    lng: -4,
  },
  {
    id: 'de',
    iso2: 'DE',
    names: { en: 'Germany', ru: 'Germany' },
    capitals: { en: 'Berlin', ru: 'Berlin' },
    continent: 'europe',
    lat: 52,
    lng: 13,
  },
  {
    id: 'fr',
    iso2: 'FR',
    names: { en: 'France', ru: 'France' },
    capitals: { en: 'Paris', ru: 'Paris' },
    continent: 'europe',
    lat: 48,
    lng: 2,
  },
  {
    id: 'ng',
    iso2: 'NG',
    names: { en: 'Nigeria', ru: 'Nigeria' },
    capitals: { en: 'Abuja', ru: 'Abuja' },
    continent: 'africa',
    lat: 9,
    lng: 8,
  },
  {
    id: 'cn',
    iso2: 'CN',
    names: { en: 'China', ru: 'China' },
    capitals: { en: 'Beijing', ru: 'Beijing' },
    continent: 'asia',
    lat: 35,
    lng: 105,
  },
];

export const FIXTURE_KNOWLEDGE: Record<string, CountryKnowledgeEntry> = {
  ES: {
    iso2: 'ES',
    languages: ['Spanish'],
    currencyCode: 'EUR',
    currencyName: { en: 'Euro' },
    population: 47_000_000,
    areaKm2: 505_990,
    subregion: { en: 'Southern Europe' },
    facts: [],
  },
  DE: {
    iso2: 'DE',
    languages: ['German'],
    currencyCode: 'EUR',
    currencyName: { en: 'Euro' },
    population: 83_000_000,
    areaKm2: 357_022,
    subregion: { en: 'Western Europe' },
    facts: [],
  },
  FR: {
    iso2: 'FR',
    languages: ['French'],
    currencyCode: 'EUR',
    currencyName: { en: 'Euro' },
    population: 67_000_000,
    areaKm2: 551_695,
    subregion: { en: 'Western Europe' },
    facts: [],
  },
  NG: {
    iso2: 'NG',
    languages: ['English'],
    currencyCode: 'NGN',
    currencyName: { en: 'Naira' },
    population: 220_000_000,
    areaKm2: 923_768,
    subregion: { en: 'Western Africa' },
    facts: [],
  },
  CN: {
    iso2: 'CN',
    languages: ['Mandarin'],
    currencyCode: 'CNY',
    currencyName: { en: 'Yuan' },
    population: 1_400_000_000,
    areaKm2: 9_596_961,
    subregion: { en: 'Eastern Asia' },
    facts: [],
  },
};
